### ISSUE TITLE
mix appsignal.install fails due SSL handshake error

### ISSUE THREAD

**Issue by navinpeiris** [appsignal/appsignal-elixir#981]
## Describe the bug

When trying to run `mix appsignal.install` on a new project, it fails with the following error:

```bash
Validating Push API key:
09:04:06.354 [notice] TLS :client: In state :certify at ssl_handshake.erl:2186 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert,
 {:hostname_check_failed, {:requested, {185, 191, 3, 125}},
  {:received, [dNSName: ~c"push.appsignal.com"]}}}

Validating failed, reason:

  {:tls_alert, {:handshake_failure, ~c"TLS client: In state certify at ssl_handshake.erl:2186 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,\n     {hostname_check_failed,\n         {requested,{185,191,3,125}},\n         {received,[{dNSName,\"push.appsignal.com\"}]}}}"}}

```

## To Reproduce

- Generate a new project using `mix new xyz`
- Add dependency `{:appsignal, "2.13.4"}`
- Run `mix deps.get`
- Run `mix appsignal.install <your-api-key>`

**Comment by patrickjaberg** [comment]
FWIW, I think this is related to `hackney` version `1.22.0` that was recently released.   Locking to version `1.21.0` should allow things to work (at least it did for us).

**Comment by patrickjaberg** [comment]
For maintainers -- we also ran into these TLS connection issues when compiling, as the platform-specific NIF would silently fail to download, resulting in loss of deploy/error/performance reporting.  The TLS issue also surfaced when trying to submit a report from the diagnostic tool (`:appsignal_tasks.diagnose()`).

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/unassigned/conversation/16410700399193?view=List (private link)

**Comment by luismiramirez** [comment]
I've opened an issue on Hackney's side. In the meantime, use `1.21.0` as we've confirmed everything works in that version.

https://github.com/benoitc/hackney/issues/759

**Comment by luismiramirez** [comment]
Version [v2.14.0](https://hex.pm/packages/appsignal/2.14.0) of the integration automatically limits Hackney version.

**Comment by navinpeiris** [comment]
Thanks @luismiramirez. Just FYI, if you've only got `appsignal_phoenix` in your dependency list, the new restriction results in `certifi` and `hackney` being updated while gets left `appsignal` left at `2.13.4`.

**Comment by luismiramirez** [comment]
A fix is on the way: https://github.com/benoitc/hackney/pull/760

I've tested the branch and it fixes the issue.

**Comment by ghenry** [comment]
Got this yesterday :-) Great work!

**Comment by pepicrft** [comment]
Thanks for fixing this one.

**Comment by navinpeiris** [comment]
New hackney version with the fix has been released @luismiramirez: https://github.com/benoitc/hackney/releases/tag/1.23.0

**Comment by oliver-kriska** [comment]
for the record(others), we still have issue with latest Hackney, downgrading Hackney is temporary help
```
appsignal 2.13.3 => 2.14.0
hackney 1.22.0 => 1.21.0
```

**Comment by luismiramirez** [comment]
Looks like POST requests are still broken. Already reported it in the Hackney repo. The current trustable solution is still using Appsignal for Elixir `2.14.0`, which locks the Hackney version to `1.21.0`

**Comment by luismiramirez** [comment]
[v2.15.0](https://hex.pm/packages/appsignal/2.15.0) uses Finch instead of Hackney to perform HTTP requests. The handshake error should be gone now.
